# -*- coding: utf-8 -*-
"""AI Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ZyJBLRMpdAtkdOMALHCVIGK7nSygLaH

### **Importing of the necesary libraries**
"""

from sklearn.metrics import mean_squared_error
import xgboost
import pandas

"""### **Importing of the dataset**"""

dataset = pandas.read_csv('/content/sample_data/california_housing_train.csv')
dataset

X = dataset.loc[:, dataset.columns != "median_house_value"]
y = dataset["median_house_value"]

"""### **Model building**"""

model = xgboost.XGBRegressor()
model.fit(X, y)

"""### **Model evaluation**"""

test_dataset = pandas.read_csv('/content/sample_data/california_housing_test.csv')
X_test = test_dataset.loc[:, test_dataset.columns != "median_house_value"]
y_test = test_dataset["median_house_value"]

pred = model.predict(X_test)

print(mean_squared_error(y_test, pred))